[project]
name = "diffsqp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bard",
    "cvxpylayers>=1.0.1",
    "matplotlib>=3.10.8",
    "opt-einsum>=3.4.0",
    "pyyaml>=6.0.3",
    "torch>=2.10.0",
    "torchvision>=0.25.0",
    "viser>=1.0.21",
]

[tool.uv.sources]
bard = { git = "https://github.com/YueWang996/bard-pytorch-dynamics" }
