system:
  name: cartpole

  n_x: 4 # Number of state elements
  n_q: 2 # Number of position elements in state
  n_v: 2 # Number of velocity elements in state
  n_j: 2 # Number of joints
  n_u: 1 # Number of DoF

  mc: 0.5
  mp: 0.3
  lp: 0.2
  grav: 9.81

problem:
  inverse_dynamics: True
  n_h: 1 # Number of underactuated DoFs
  n_batch: 3 # batch size
  dt: 0.01 # node dt
  tf: 1.0 # total horizon time

  # Initial and final states
  x_init: [0.0, 0.0, 0.0, 0.0]
  x_des: [0.0, 3.14159, 0.0, 0.0]
  noise_std: 0.1 # initial state noise std

  # Cost weights
  q_w: [1.0E-6, 1.0E-6, 1.0E-6, 1.0E-6]
  r_w: [1.0E-3, 1.0E-3]
  qf_w: [1.0E+5, 1.0E+5, 1.0E+5, 1.0E+5]

solver:
  # Solver parameters
  sqp_max_iter: 500
  merit_mu: 1.0E+6
  ls_max_iter: 10
  sqp_eps: 1.0E-4
  qp_solver: "lqr"
  ls_function: "filter"
